### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Afaner9527** [UgurhanK/BaseBuilder#2]
The author, please fix the issue with the 2.3 and 2.2 version plugins not mounting effectively when you have time.

**Comment by aadsa** [comment]
![Uploading 1.png…]()

**Comment by aadsa** [comment]
![Uploading 2.png…]()

**Comment by aadsa** [comment]
服务器插件不载入

**Comment by aadsa** [comment]
The author, please fix the issue with the 2.3 and 2.2 version plugins not mounting effectively when you have time.
